---
driver:
  name: vagrant
  customize:
    memory: 7000
    cpuexecutioncap: 90
    cpus: 1
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"

  network:
#  - ["forwarded_port", {guest: 57070, host: 50070}]
#  - ["forwarded_port", {guest: 57075, host: 50075}]
#  - ["forwarded_port", {guest: 3306, host: 3308}]
  
provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
#  - name: ubuntu-15.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[ndb::install]
      - recipe[hops::install]
      - recipe[ndb::mgmd]
      - recipe[ndb::ndbd]
      - recipe[ndb::mysqld]
      - recipe[hops::ndb]
      - recipe[hops::nn]
      - recipe[hops::dn]
      - recipe[hops::rm]
      - recipe[hops::nm]
      - recipe[hops::jhs]

    attributes:
         vagrant: "true"
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            dir: "/tmp"
         ndb:
            mgmd:
               private_ips: ["10.0.2.15"]
            ndbd:
               private_ips: ["10.0.2.15"]
            mysqld:
               private_ips: ["10.0.2.15"]
            memcached:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            enabled: "true"
            dir: "/tmp"
         hops:
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            use_hopsworks: "true"
            dir: "/tmp"
         apache_hadoop:
            nn:
               private_ips: ["10.0.2.15"]
               direct_memory_size: 300
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            dir: "/tmp"
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
